services:
  minfo:
    build: .
    privileged: true
    ports:
      - "28081:8080"
    environment:
      PORT: "8080"
      WEB_PASSWORD: "adminadmin"
    volumes:
      - /home/mirrorb/qbittorrent/Downloads:/media:ro
